package com.travelmemory.controller;
import com.travelmemory.common.Result;import com.travelmemory.dto.*;import com.travelmemory.security.CurrentUser;import com.travelmemory.security.UserPrincipal;import com.travelmemory.service.AppUserService;
import jakarta.servlet.http.HttpServletRequest;import jakarta.servlet.http.HttpSession;import jakarta.validation.Valid;import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.security.web.csrf.CsrfToken;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/auth") public class AuthController{
 private final AppUserService users;private final CurrentUser current;public AuthController(AppUserService users,CurrentUser current){this.users=users;this.current=current;}
 @GetMapping("/csrf") public Result<Void> csrf(CsrfToken token){token.getToken();return Result.success();}
 @GetMapping("/registration-status") public Result<RegistrationStatusResponse> registrationStatus(){return Result.success(users.registrationStatus());}
 @PostMapping("/register") public Result<CurrentUserResponse> register(@Valid @RequestBody RegisterRequest request,HttpServletRequest servlet){UserPrincipal user=users.register(request);servlet.getSession();servlet.changeSessionId();SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(user,null,user.getAuthorities()));return Result.success(CurrentUserResponse.from(user));}
 @PostMapping("/login") public Result<CurrentUserResponse> login(@Valid @RequestBody LoginRequest request,HttpServletRequest servlet){UserPrincipal user=users.authenticate(request.getUsername(),request.getPassword());servlet.getSession();servlet.changeSessionId();SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(user,null,user.getAuthorities()));return Result.success(CurrentUserResponse.from(user));}
 @GetMapping("/me") public Result<CurrentUserResponse> me(){return Result.success(CurrentUserResponse.from(current.require()));}
 @PostMapping("/logout") public Result<Void> logout(HttpServletRequest request){HttpSession session=request.getSession(false);if(session!=null)session.invalidate();SecurityContextHolder.clearContext();return Result.success();}
 @PutMapping("/password") public Result<Void> changePassword(@Valid @RequestBody PasswordChangeRequest request,HttpServletRequest servlet){Long userId=current.requireId();users.changePassword(userId,request.getCurrentPassword(),request.getNewPassword());servlet.getSession();servlet.changeSessionId();UserPrincipal refreshed=users.currentPrincipal(userId);SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(refreshed,null,refreshed.getAuthorities()));return Result.success();}
}
